services:
  service:
    build:
      context: ../../
      dockerfile: .docker/development/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ../..:/workspaces/app:cached
    networks:
      - network_development
    ports:
      -"50000-50100:50000-50100"
    depends_on:
      kafka:
        condition: service_healthy
    env_file:
      - .env.${APP_ENV}
    command: "sleep infinity"

  kafka:
    image: apache/kafka-native:3.9.0
    ports:
      - '9092:9092'
      - '9093:9093'
    env_file:
      - .env.${APP_ENV}
    networks:
      - network_development
    healthcheck:
      test: [ "CMD", "sh", "-c", "nc -z localhost 9092" ]
      interval: 30s
      timeout: 5s
      retries: 3
    # environment:
    #   # Kafka environment variables override
    #   # e.g., KAFKA_ADVERTISED_LISTENER, KAFKA_LISTENER_PORT, etc.

networks:
  network_development:
    driver: bridge
